.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bether_qt test_bether_qt
clean: FORCE
	$(MAKE) -C .. bether_qt_clean test_bether_qt_clean
check: FORCE
	$(MAKE) -C .. test_bether_qt_check
bether-qt bether-qt.exe: FORCE
	 $(MAKE) -C .. bether_qt
